// P&J GLASS - ACCESSORIES DATABASE
// CRL-inspired glass hardware & accessories with placeholder pricing

import { getSalePrice, SALE_DISCOUNT } from './products';

export const accessoryCategories = {
  showerAccessories: {
    name: 'Shower Hardware',
    slug: 'shower-hardware',
    description: 'Premium shower door hinges, handles, support bars & seals',
  },
  mirrorAccessories: {
    name: 'Mirror Accessories',
    slug: 'mirror-accessories',
    description: 'Mirror mounting kits, adhesives, clips & heated defogger pads',
  },
  balustradeAccessories: {
    name: 'Balustrade Fittings',
    slug: 'balustrade-fittings',
    description: 'Glass clamps, railing clamps, standoffs & handrails',
  },
  sealantsCleaning: {
    name: 'Sealants & Cleaning',
    slug: 'sealants-cleaning',
    description: 'Glass sealants, cleaners, glazing tapes & easy-clean coatings',
  },
  doorHardware: {
    name: 'Door Hardware',
    slug: 'door-hardware',
    description: 'Glass door pull handles, patch fittings, pivot sets & push plates',
  },
  partitionHardware: {
    name: 'Partition Hardware',
    slug: 'partition-hardware',
    description: 'Office partition clamps, header channels, connectors & track systems',
  },
  barnDoorHardware: {
    name: 'Barn Door & Sliding Hardware',
    slug: 'barn-door-hardware',
    description: 'Sliding glass door track kits, rollers, soft-close mechanisms & floor guides',
  },
  glazingTools: {
    name: 'Glazing Tools & Supplies',
    slug: 'glazing-tools',
    description: 'Suction lifters, glass cutters, pliers, corner protectors & installation tools',
  },
  showerEnclosures: {
    name: 'Shower Screen Systems',
    slug: 'shower-screen-systems',
    description: 'Walk-in wetroom panels, Crittall-style grid screens & sliding shower kits',
  },
};

// ─── Shower Accessories ──────────────────────────────────────

const showerAccessories = [
  { id: 'acc-shower-hinge-bellagio-90-wall', name: 'Bellagio 90° Wall-to-Glass Shower Hinge — Chrome', category: 'showerAccessories', shortDesc: 'Premium 90° wall-mounted shower hinge for frameless glass doors. Suitable for 8–10mm toughened glass. Adjustable for a perfect fit.', priceFrom: 42, priceTo: null, priceDisplay: '£42.00', image: 'https://www.egw.co.uk/cdn/shop/products/chrome-shower-door-hinge-wall-mounted-90_1200x1200.jpg?v=1669802012', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-hinge-bellagio-180-gg', name: 'Bellagio 180° Glass-to-Glass Shower Hinge — Chrome', category: 'showerAccessories', shortDesc: '180° glass-to-glass shower hinge for inline frameless shower enclosures. Supports 8–10mm glass panels.', priceFrom: 55, priceTo: null, priceDisplay: '£55.00', image: 'https://www.egw.co.uk/cdn/shop/products/APH-H09_1200x655.jpg?v=1614176179', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-hinge-murano-90-wall', name: 'Murano 90° Wall-to-Glass Shower Hinge — Matt Black', category: 'showerAccessories', shortDesc: 'Contemporary square-profile 90° shower door hinge in matt black finish. For 8–10mm frameless glass.', priceFrom: 48, priceTo: null, priceDisplay: '£48.00', image: 'https://www.egw.co.uk/cdn/shop/products/SH-NKE-H01_Bblackglasstowallhingeconcealedfixings_7478d766-325a-42b5-87fe-67b6d4411744_1200x1200.jpg?v=1672995526', fitsWith: ['bathScreens'], finishes: ['Matt Black', 'Chrome', 'Brushed Brass'], brand: 'CRL' },
  { id: 'acc-shower-knob-round-30mm', name: 'Round 30mm Back-to-Back Shower Door Knob', category: 'showerAccessories', shortDesc: 'Sleek 30mm round shower door knob set (back-to-back). Suitable for 6–10mm toughened glass.', priceFrom: 14, priceTo: null, priceDisplay: '£14.00', image: 'https://www.egw.co.uk/cdn/shop/products/SHAPHK01-1024x559_1200x655.jpg?v=1601033349', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-knob-square-30mm', name: 'Square 30mm Back-to-Back Shower Door Knob', category: 'showerAccessories', shortDesc: 'Modern square 30mm shower door knob set. Back-to-back mounting for 6–10mm glass panels.', priceFrom: 18, priceTo: null, priceDisplay: '£18.00', image: 'https://www.egw.co.uk/cdn/shop/products/APH-K12_1200x655.jpg?v=1601979014', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-pull-handle-tubular-300', name: 'Tubular Pull Handle 300mm — Shower Door', category: 'showerAccessories', shortDesc: '300mm tubular stainless steel pull handle for frameless shower doors. Single-sided or back-to-back mounting.', priceFrom: 22, priceTo: null, priceDisplay: '£22.00', image: 'https://www.egw.co.uk/cdn/shop/files/6-inch-d-shaped-shower-door-handles_1200x1200.jpg?v=1726737804', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-pull-handle-square-300', name: 'Square Pull Handle 300mm — Shower Door', category: 'showerAccessories', shortDesc: '300mm square-profile pull handle for glass shower doors. Premium stainless steel construction.', priceFrom: 32, priceTo: null, priceDisplay: '£32.00', image: 'https://www.egw.co.uk/cdn/shop/products/GGA-P05_1200x676.jpg?v=1601990013', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-towel-bar-600', name: 'Towel Bar 600mm — Glass Mounted', category: 'showerAccessories', shortDesc: '600mm towel bar designed to mount on frameless glass shower panels. Stainless steel construction.', priceFrom: 28, priceTo: null, priceDisplay: '£28.00', image: 'https://www.egw.co.uk/cdn/shop/products/3068SH-GGA-P01_1200x655.jpg?v=1601987806', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-support-bar-round-1000', name: 'Round Support Bar 1000mm — Wall-to-Glass', category: 'showerAccessories', shortDesc: '1000mm round support bar for frameless glass shower panels. Adjustable angle wall bracket included.', priceFrom: 35, priceTo: null, priceDisplay: '£35.00', image: 'https://www.egw.co.uk/cdn/shop/products/SHAPHT03-AD_1200x655.jpg?v=1614770844', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-support-bar-square-1200', name: 'Square Support Bar 1200mm — Wall-to-Glass', category: 'showerAccessories', shortDesc: '1200mm square-profile support bar. Complete wall-to-glass set with adjustable brackets. For 8–10mm glass.', priceFrom: 45, priceTo: null, priceDisplay: '£45.00', image: 'https://www.egw.co.uk/cdn/shop/products/SHAPHT03-AD_1200x655.jpg?v=1614770844', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-u-channel-dry-2000', name: 'U-Channel Dry Glaze 2000mm — Floor Mount', category: 'showerAccessories', shortDesc: '2000mm aluminium U-channel for dry-glazing frameless shower panels to the floor. For 8–10mm glass.', priceFrom: 22, priceTo: null, priceDisplay: '£22.00', image: 'https://www.egw.co.uk/cdn/shop/products/blackchannel_1200x1200.jpg?v=1677168098', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-seal-curved-2000', name: 'Curved Shower Seal Strip 2000mm', category: 'showerAccessories', shortDesc: 'Flexible curved shower door seal strip. Prevents water leakage at bottom of frameless shower doors. For 6–10mm glass.', priceFrom: 9, priceTo: null, priceDisplay: '£9.00', image: 'https://www.egw.co.uk/cdn/shop/files/Translucent-Glass-To-Floor-Seals_1200x1200.webp?v=1727685845', fitsWith: ['bathScreens'], finishes: [], brand: 'CRL' },
  { id: 'acc-shower-seal-magnetic-2000', name: 'Magnetic Shower Door Seal Pair 2000mm', category: 'showerAccessories', shortDesc: 'Pair of magnetic seals for double shower doors. Creates a watertight closure. For 6–8mm glass.', priceFrom: 15, priceTo: null, priceDisplay: '£15.00', image: 'https://www.egw.co.uk/cdn/shop/files/Magnetic-Seals-Main-Image_1200x1200.webp?v=1727688902', fitsWith: ['bathScreens'], finishes: [], brand: 'CRL' },
  { id: 'acc-shower-threshold-1000', name: 'Shower Door Threshold Strip 1000mm', category: 'showerAccessories', shortDesc: 'Low-profile aluminium threshold strip to contain water at the shower entrance. Sloped for wheelchair access.', priceFrom: 18, priceTo: null, priceDisplay: '£18.00', image: 'https://www.egw.co.uk/cdn/shop/files/Bubble-Seal-Main-Image_1200x1200.jpg?v=1727688066', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-glass-clamp-square', name: 'Square Glass Clamp — Shower Panel', category: 'showerAccessories', shortDesc: 'Square glass-to-wall clamp for fixed shower panels. Zinc alloy with stainless steel finish. For 8–10mm glass.', priceFrom: 12, priceTo: null, priceDisplay: '£12.00', image: 'https://www.egw.co.uk/cdn/shop/products/ATB-B-S-Fbrushedbalustradeclamp_1200x655.jpg?v=1601373163', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-hinge-135-corner', name: '135° Glass-to-Glass Corner Hinge — Chrome', category: 'showerAccessories', shortDesc: '135° corner hinge for angled frameless shower enclosures. Heavy-duty zinc alloy. For 8–10mm toughened glass.', priceFrom: 52, priceTo: null, priceDisplay: '£52.00', image: 'https://www.egw.co.uk/cdn/shop/products/APH-H09_1200x655.jpg?v=1614176179', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-hinge-bifold-wall', name: 'Bi-Fold Shower Door Hinge Set — Wall-to-Glass', category: 'showerAccessories', shortDesc: 'Bi-fold hinge set for inward-folding shower doors. Saves space in small bathrooms. For 6–8mm glass.', priceFrom: 65, priceTo: null, priceDisplay: '£65.00', image: 'https://www.egw.co.uk/cdn/shop/products/chrome-shower-door-hinge-wall-mounted-90_1200x1200.jpg?v=1669802012', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-hinge-lift-off-90', name: '90° Lift-Off Shower Hinge — Wall Mount', category: 'showerAccessories', shortDesc: 'Lift-off 90° shower hinge for easy door removal and cleaning. Rise-and-fall mechanism. For 8–10mm glass.', priceFrom: 58, priceTo: null, priceDisplay: '£58.00', image: 'https://www.egw.co.uk/cdn/shop/products/chrome-shower-door-hinge-wall-mounted-90_1200x1200.jpg?v=1669802012', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Brass'], brand: 'CRL' },
  { id: 'acc-shower-hinge-murano-180-gg', name: 'Murano 180° Glass-to-Glass Hinge — Matt Black', category: 'showerAccessories', shortDesc: 'Square-profile 180° glass-to-glass hinge in matt black. Modern minimal design. For 8–10mm glass.', priceFrom: 62, priceTo: null, priceDisplay: '£62.00', image: 'https://www.egw.co.uk/cdn/shop/products/SH-NKE-H01_Bblackglasstowallhingeconcealedfixings_7478d766-325a-42b5-87fe-67b6d4411744_1200x1200.jpg?v=1672995526', fitsWith: ['bathScreens'], finishes: ['Matt Black', 'Chrome', 'Brushed Brass'], brand: 'CRL' },
  { id: 'acc-shower-hinge-bellagio-90-gg', name: 'Bellagio 90° Glass-to-Glass Hinge — Chrome', category: 'showerAccessories', shortDesc: '90° glass-to-glass hinge for shower side panels. Bellagio rounded profile. For 8–10mm toughened glass.', priceFrom: 50, priceTo: null, priceDisplay: '£50.00', image: 'https://www.egw.co.uk/cdn/shop/products/APH-H09_1200x655.jpg?v=1614176179', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-hinge-soft-close', name: 'Soft-Close 90° Shower Hinge — Wall-to-Glass', category: 'showerAccessories', shortDesc: 'Premium 90° shower hinge with built-in soft-close damper. Prevents slamming. For 8–10mm glass.', priceFrom: 78, priceTo: null, priceDisplay: '£78.00', image: 'https://www.egw.co.uk/cdn/shop/products/chrome-shower-door-hinge-wall-mounted-90_1200x1200.jpg?v=1669802012', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-hinge-brushed-brass-90', name: '90° Wall-to-Glass Hinge — Brushed Brass', category: 'showerAccessories', shortDesc: 'Luxurious brushed brass 90° shower hinge. On-trend warm metallic finish. For 8–10mm toughened glass.', priceFrom: 56, priceTo: null, priceDisplay: '£56.00', image: 'https://www.egw.co.uk/cdn/shop/products/chrome-shower-door-hinge-wall-mounted-90_1200x1200.jpg?v=1669802012', fitsWith: ['bathScreens'], finishes: ['Brushed Brass'], brand: 'CRL' },
  { id: 'acc-shower-hinge-brushed-nickel-90', name: '90° Wall-to-Glass Hinge — Brushed Nickel', category: 'showerAccessories', shortDesc: 'Contemporary brushed nickel 90° shower hinge. Satin-finish metal for modern bathrooms. For 8–10mm glass.', priceFrom: 50, priceTo: null, priceDisplay: '£50.00', image: 'https://www.egw.co.uk/cdn/shop/products/chrome-shower-door-hinge-wall-mounted-90_1200x1200.jpg?v=1669802012', fitsWith: ['bathScreens'], finishes: ['Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-pivot-hinge-floor-ceil', name: 'Floor-to-Ceiling Pivot Hinge Set', category: 'showerAccessories', shortDesc: 'Floor-to-ceiling pivot hinge set for full-height frameless shower doors. Adjustable spring tension. For 8–10mm glass.', priceFrom: 85, priceTo: null, priceDisplay: '£85.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Pivot+Hinge+Set', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-header-bar-2000', name: 'Shower Header Bar 2000mm — Glass-to-Wall', category: 'showerAccessories', shortDesc: '2000mm overhead header bar connecting glass panel to wall. Provides structural support for walk-in showers. For 8–10mm glass.', priceFrom: 48, priceTo: null, priceDisplay: '£48.00', image: 'https://www.egw.co.uk/cdn/shop/products/SHAPHT03-AD_1200x655.jpg?v=1614770844', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-shower-slider-kit-1500', name: 'Sliding Shower Door Kit 1500mm — Complete', category: 'showerAccessories', shortDesc: 'Complete sliding shower door hardware kit. 1500mm track with rollers, guides and stoppers. For 8mm glass.', priceFrom: 125, priceTo: null, priceDisplay: '£125.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Slider+Kit+1500', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-slider-kit-1800', name: 'Sliding Shower Door Kit 1800mm — Complete', category: 'showerAccessories', shortDesc: 'Complete sliding shower door hardware kit. 1800mm track with rollers, guides and stoppers. For 8mm glass.', priceFrom: 145, priceTo: null, priceDisplay: '£145.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Slider+Kit+1800', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-shower-roller-top-pair', name: 'Top-Hung Shower Door Roller Pair', category: 'showerAccessories', shortDesc: 'Pair of replacement top-hung rollers for sliding shower doors. Stainless steel bearings. Silent operation.', priceFrom: 22, priceTo: null, priceDisplay: '£22.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Shower+Rollers', fitsWith: ['bathScreens'], finishes: ['Chrome'], brand: 'CRL' },
  { id: 'acc-shower-roller-bottom-guide', name: 'Bottom Guide for Sliding Shower Door', category: 'showerAccessories', shortDesc: 'Adjustable bottom guide block for sliding shower doors. Prevents swinging. Clear polycarbonate construction.', priceFrom: 8, priceTo: null, priceDisplay: '£8.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Bottom+Guide', fitsWith: ['bathScreens'], finishes: [], brand: 'CRL' },
];

// ─── Mirror Accessories ──────────────────────────────────────

const mirrorAccessories = [
  { id: 'acc-mirror-mount-kit-professional', name: 'Professional Mirror Mounting Kit', category: 'mirrorAccessories', shortDesc: 'Complete mirror mounting kit with Z-clips, screws, wall plugs and spacers. Suitable for mirrors up to 20kg.', priceFrom: 22, priceTo: null, priceDisplay: '£22.00', image: 'https://www.egw.co.uk/cdn/shop/products/BohleSelfSupports-BO5207331_1200x1084.jpg?v=1642782719', fitsWith: ['mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-mirror-mount-kit-heavy-duty', name: 'Heavy-Duty Mirror Mounting Kit', category: 'mirrorAccessories', shortDesc: 'Heavy-duty Z-clip mounting kit for large mirrors and gym mirrors. Supports mirrors up to 40kg. Includes all fixings.', priceFrom: 32, priceTo: null, priceDisplay: '£32.00', image: 'https://www.egw.co.uk/cdn/shop/products/BohleSelfSupports-BO5207331_1200x1084.jpg?v=1642782719', fitsWith: ['mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-mirror-adhesive-evergrip', name: 'EverGrip Premium Mirror Adhesive 310ml', category: 'mirrorAccessories', shortDesc: 'Professional-grade mirror adhesive. Safe for silvered mirrors — will not damage backing. 310ml cartridge.', priceFrom: 10, priceTo: null, priceDisplay: '£10.00', image: 'https://www.egw.co.uk/cdn/shop/products/SplashbackandMirrorGlue_1200x1200.png?v=1641814102', fitsWith: ['mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-mirror-adhesive-ms-polymer', name: 'MS Polymer Mirror Adhesive 290ml', category: 'mirrorAccessories', shortDesc: 'High-performance MS polymer adhesive for mirrors. Solvent-free, mirror-safe formula. Crystal clear finish.', priceFrom: 12, priceTo: null, priceDisplay: '£12.00', image: 'https://www.egw.co.uk/cdn/shop/products/SplashbackandMirrorGlue_1200x1200.png?v=1641814102', fitsWith: ['mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-mirror-foam-tape-roll', name: 'Double-Sided Mirror Foam Tape 25mm × 5m', category: 'mirrorAccessories', shortDesc: 'Double-sided foam mounting tape for mirrors. 25mm wide × 5m roll. For lightweight mirror panels.', priceFrom: 7, priceTo: null, priceDisplay: '£7.00', image: 'https://www.egw.co.uk/cdn/shop/products/SplashbackandMirrorGlue_1200x1200.png?v=1641814102', fitsWith: ['mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-mirror-clips-ez-mount-set', name: 'E-Z Mount Mirror Clip Set (4 Pack)', category: 'mirrorAccessories', shortDesc: 'Set of 4 E-Z Mount mirror clips with screws. Spring-loaded for secure hold. Chrome finish.', priceFrom: 8, priceTo: null, priceDisplay: '£8.00', image: 'https://www.egw.co.uk/cdn/shop/products/MirrorDomeHeadScrew_1200x894.jpg?v=1623667169', fitsWith: ['mirrors'], finishes: ['Chrome'], brand: 'CRL' },
  { id: 'acc-mirror-clips-decorative-set', name: 'Decorative Mirror Clip Set (4 Pack) — Round', category: 'mirrorAccessories', shortDesc: 'Set of 4 decorative round mirror clips. Polished chrome finish. For 4–6mm mirrors.', priceFrom: 12, priceTo: null, priceDisplay: '£12.00', image: 'https://www.egw.co.uk/cdn/shop/products/MirrorDomeHeadScrew_1200x894.jpg?v=1623667169', fitsWith: ['mirrors'], finishes: ['Chrome', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-mirror-defogger-pad-small', name: 'Heated Mirror Defogger Pad — Small (300×400mm)', category: 'mirrorAccessories', shortDesc: 'Electric heated pad that sticks behind your mirror to prevent condensation. 300×400mm, 35W. IP44 rated.', priceFrom: 28, priceTo: null, priceDisplay: '£28.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-mirror-defogger-pad-large', name: 'Heated Mirror Defogger Pad — Large (500×700mm)', category: 'mirrorAccessories', shortDesc: 'Large electric heated defogger pad for bathroom mirrors. 500×700mm, 65W. Easy peel-and-stick installation.', priceFrom: 42, priceTo: null, priceDisplay: '£42.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-mirror-safety-backing-film', name: 'Mirror Safety Backing Film — Roll (1m × 2m)', category: 'mirrorAccessories', shortDesc: 'Self-adhesive safety backing film for mirrors. Prevents shattering. BS 6206 / EN 12600 compliant. 1m × 2m roll.', priceFrom: 15, priceTo: null, priceDisplay: '£15.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-mirror-j-channel-2000', name: 'Mirror J-Channel 2000mm — Wall Mount', category: 'mirrorAccessories', shortDesc: 'Aluminium J-channel for bottom-mounting mirrors to walls. 2000mm length. For 4–6mm mirrors.', priceFrom: 14, priceTo: null, priceDisplay: '£14.00', image: 'https://www.egw.co.uk/cdn/shop/products/blackchannel_1200x1200.jpg?v=1677168098', fitsWith: ['mirrors'], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-mirror-led-strip-kit', name: 'LED Backlight Strip Kit for Mirrors', category: 'mirrorAccessories', shortDesc: 'Warm white LED strip kit for creating backlit mirror effects. 2m strip with driver. IP44 rated for bathrooms.', priceFrom: 35, priceTo: null, priceDisplay: '£35.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['mirrors'], finishes: [], brand: 'P&J Glass' },
];

// ─── Balustrade Accessories ──────────────────────────────────

const balustradeAccessories = [
  { id: 'acc-balustrade-clamp-square-45', name: 'Square Glass Clamp 45×45mm — Flat Back', category: 'balustradeAccessories', shortDesc: 'Square 45×45mm flat-back glass clamp for balustrades. 316 stainless steel. For 8–12mm glass.', priceFrom: 18, priceTo: null, priceDisplay: '£18.00', image: 'https://www.egw.co.uk/cdn/shop/products/ATB-B-S-Fbrushedbalustradeclamp_1200x655.jpg?v=1601373163', fitsWith: ['balustrades'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
  { id: 'acc-balustrade-clamp-square-55', name: 'Square Glass Clamp 55×55mm — Flat Back', category: 'balustradeAccessories', shortDesc: 'Large 55×55mm flat-back glass clamp for balustrades and partitions. 316 stainless steel. For 10–17mm glass.', priceFrom: 24, priceTo: null, priceDisplay: '£24.00', image: 'https://www.egw.co.uk/cdn/shop/products/ATB-B-S-Fbrushedbalustradeclamp_1200x655.jpg?v=1601373163', fitsWith: ['balustrades'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
  { id: 'acc-balustrade-clamp-d-shape', name: 'D-Shape Glass Clamp — Round Back', category: 'balustradeAccessories', shortDesc: 'D-shape glass clamp with round back for post mounting. 316 stainless steel. For 8–12mm glass.', priceFrom: 16, priceTo: null, priceDisplay: '£16.00', image: 'https://www.egw.co.uk/cdn/shop/products/SH-ATB-B-Dbrushedstainlesssteelroundbackbalustradeclamp_1200x655.jpg?v=1601302048', fitsWith: ['balustrades'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
  { id: 'acc-balustrade-railing-clamp-round', name: 'Round Railing Clamp — Top Mount', category: 'balustradeAccessories', shortDesc: 'Round top-mount railing clamp for connecting handrails to glass balustrade panels. 316 stainless steel.', priceFrom: 28, priceTo: null, priceDisplay: '£28.00', image: 'https://www.egw.co.uk/cdn/shop/products/2204SH-ATB-GF03_XLHeavydutystainlesssteeloffsetfitting_1200x655.jpg?v=1601380199', fitsWith: ['balustrades', 'julietBalconies'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
  { id: 'acc-balustrade-standoff-50mm', name: 'Glass Standoff Pin 50mm', category: 'balustradeAccessories', shortDesc: '50mm glass standoff pin for point-fixing glass panels. 316 stainless steel. For 10–12mm glass. Set of 4.', priceFrom: 35, priceTo: null, priceDisplay: '£35.00', image: 'https://www.egw.co.uk/cdn/shop/products/2204SH-ATB-GF03_XLHeavydutystainlesssteeloffsetfitting_1200x655.jpg?v=1601380199', fitsWith: ['balustrades'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
  { id: 'acc-balustrade-standoff-25mm', name: 'Glass Standoff Pin 25mm — Countersunk', category: 'balustradeAccessories', shortDesc: '25mm countersunk glass standoff pin. Sleek flush design. 316 stainless steel. For 10–12mm glass. Set of 4.', priceFrom: 30, priceTo: null, priceDisplay: '£30.00', image: 'https://www.egw.co.uk/cdn/shop/products/6083SH-ATB-GF03stainlesssteeloffsetbalustradefittingonstaircase_1200x655.jpg?v=1601307818', fitsWith: ['balustrades'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
  { id: 'acc-balustrade-handrail-round-1000', name: 'Round Stainless Steel Handrail 1000mm', category: 'balustradeAccessories', shortDesc: '42.4mm diameter round stainless steel handrail. 1000mm length. Includes end caps. Cut-to-size available.', priceFrom: 45, priceTo: null, priceDisplay: '£45.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['balustrades', 'julietBalconies'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
  { id: 'acc-balustrade-handrail-round-2000', name: 'Round Stainless Steel Handrail 2000mm', category: 'balustradeAccessories', shortDesc: '42.4mm diameter round stainless steel handrail. 2000mm length. Includes end caps. Professional finish.', priceFrom: 75, priceTo: null, priceDisplay: '£75.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['balustrades', 'julietBalconies'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
  { id: 'acc-balustrade-gasket-rubber-roll', name: 'Rubber Gasket Strip for Glass Clamps — 5m Roll', category: 'balustradeAccessories', shortDesc: 'EPDM rubber gasket strip for glass balustrade clamps. Protects glass edges. 5m roll, suitable for 8–17mm glass.', priceFrom: 8, priceTo: null, priceDisplay: '£8.00', image: 'https://www.egw.co.uk/cdn/shop/files/Bubble-Seal-Main-Image_1200x1200.jpg?v=1727688066', fitsWith: ['balustrades'], finishes: [], brand: 'CRL' },
  { id: 'acc-balustrade-base-shoe-2500', name: 'Aluminium Base Shoe Channel 2500mm', category: 'balustradeAccessories', shortDesc: 'Aluminium base shoe channel for floor-mounting glass balustrade panels. 2500mm length. For 12–21mm glass.', priceFrom: 55, priceTo: null, priceDisplay: '£55.00', image: 'https://www.egw.co.uk/cdn/shop/products/blackchannel_1200x1200.jpg?v=1677168098', fitsWith: ['balustrades'], finishes: ['Mill Finish', 'Anodised'], brand: 'CRL' },
  { id: 'acc-balustrade-spigot-square', name: 'Square Glass Spigot — Floor Mount', category: 'balustradeAccessories', shortDesc: 'Square floor-mounted glass spigot for frameless glass balustrades. 316 stainless steel. For 12–17mm glass.', priceFrom: 38, priceTo: null, priceDisplay: '£38.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['balustrades'], finishes: ['Satin', 'Mirror Polish', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-balustrade-post-end-cap', name: 'Handrail End Cap — Flat (Pair)', category: 'balustradeAccessories', shortDesc: 'Flat end caps for 42.4mm round handrails. Sold as a pair. Push-fit design.', priceFrom: 6, priceTo: null, priceDisplay: '£6.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['balustrades', 'julietBalconies'], finishes: ['Satin', 'Mirror Polish'], brand: 'CRL' },
];

// ─── Sealants & Cleaning ─────────────────────────────────────

const sealantsCleaning = [
  { id: 'acc-sealant-silicone-clear-310', name: 'Clear Silicone Glass Sealant 310ml', category: 'sealantsCleaning', shortDesc: 'Professional-grade clear silicone sealant for glass installations. Mould-resistant. Suitable for wet areas.', priceFrom: 8, priceTo: null, priceDisplay: '£8.00', image: 'https://www.egw.co.uk/cdn/shop/products/SplashbackandMirrorGlue_1200x1200.png?v=1641814102', fitsWith: ['bathScreens', 'balustrades', 'paintedSplashbacks', 'printedSplashbacks'], finishes: [], brand: 'CRL' },
  { id: 'acc-sealant-silicone-white-310', name: 'White Silicone Glass Sealant 310ml', category: 'sealantsCleaning', shortDesc: 'White silicone sealant for glass-to-wall joints. Anti-mould formula. Perfect for shower enclosures.', priceFrom: 8, priceTo: null, priceDisplay: '£8.00', image: 'https://www.egw.co.uk/cdn/shop/products/SplashbackandMirrorGlue_1200x1200.png?v=1641814102', fitsWith: ['bathScreens', 'paintedSplashbacks', 'printedSplashbacks'], finishes: [], brand: 'CRL' },
  { id: 'acc-sealant-acrylic-clear-310', name: 'Acrylic Glass Sealant 310ml — Paintable', category: 'sealantsCleaning', shortDesc: 'Paintable acrylic sealant for glass splashbacks and interior glass installations. Low odour formula.', priceFrom: 6, priceTo: null, priceDisplay: '£6.00', image: 'https://www.egw.co.uk/cdn/shop/products/SplashbackandMirrorGlue_1200x1200.png?v=1641814102', fitsWith: ['paintedSplashbacks', 'printedSplashbacks', 'mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-cleaner-glass-spray-500', name: 'Professional Glass Cleaner Spray 500ml', category: 'sealantsCleaning', shortDesc: 'Streak-free professional glass cleaner. Safe for toughened, laminated and coated glass surfaces. 500ml spray bottle.', priceFrom: 6, priceTo: null, priceDisplay: '£6.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['bathScreens', 'mirrors', 'balustrades', 'paintedSplashbacks', 'printedSplashbacks', 'tableTopGlass'], finishes: [], brand: 'P&J Glass' },
  { id: 'acc-glazing-tape-6mm-roll', name: 'Glazing Setting Tape 6mm × 20m', category: 'sealantsCleaning', shortDesc: 'Self-adhesive glazing setting tape for glass installations. 6mm wide × 20m roll. Prevents glass-to-metal contact.', priceFrom: 5, priceTo: null, priceDisplay: '£5.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['balustrades', 'bathScreens'], finishes: [], brand: 'CRL' },
  { id: 'acc-easy-clean-coating-kit', name: 'Easy-Clean Glass Coating Kit', category: 'sealantsCleaning', shortDesc: 'Nano-technology easy-clean coating for shower glass. Repels water, limescale and soap scum. Enough for 8 sq m.', priceFrom: 22, priceTo: null, priceDisplay: '£22.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['bathScreens', 'mirrors'], finishes: [], brand: 'CRL' },
  { id: 'acc-shims-setting-blocks-bag', name: 'Glass Setting Blocks & Shims — Bag of 50', category: 'sealantsCleaning', shortDesc: 'Bag of 50 assorted plastic setting blocks and shims for glass installation. Various sizes 3–6mm.', priceFrom: 4, priceTo: null, priceDisplay: '£4.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Image+Coming+Soon', fitsWith: ['balustrades', 'bathScreens', 'julietBalconies'], finishes: [], brand: 'CRL' },
  { id: 'acc-primer-glass-metal-250', name: 'Glass & Metal Primer 250ml', category: 'sealantsCleaning', shortDesc: 'Primer for improving adhesion of sealants to glass and metal surfaces. 250ml bottle with applicator.', priceFrom: 10, priceTo: null, priceDisplay: '£10.00', image: 'https://www.egw.co.uk/cdn/shop/products/SplashbackandMirrorGlue_1200x1200.png?v=1641814102', fitsWith: ['balustrades', 'bathScreens'], finishes: [], brand: 'CRL' },
];

// ─── Door Hardware ───────────────────────────────────────────

const doorHardware = [
  { id: 'acc-door-pull-handle-600-round', name: 'Round Pull Handle 600mm — Back-to-Back', category: 'doorHardware', shortDesc: '600mm round stainless steel pull handle pair for glass doors. Back-to-back fixing for 8–12mm toughened glass.', priceFrom: 45, priceTo: null, priceDisplay: '£45.00', image: 'https://www.egw.co.uk/cdn/shop/files/6-inch-d-shaped-shower-door-handles_1200x1200.jpg?v=1726737804', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-door-pull-handle-600-square', name: 'Square Pull Handle 600mm — Back-to-Back', category: 'doorHardware', shortDesc: '600mm square-profile stainless steel pull handles. Back-to-back mounting. For 8–12mm glass doors.', priceFrom: 55, priceTo: null, priceDisplay: '£55.00', image: 'https://www.egw.co.uk/cdn/shop/products/GGA-P05_1200x676.jpg?v=1601990013', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-door-pull-handle-300-d', name: 'D-Shape Pull Handle 300mm — Single Side', category: 'doorHardware', shortDesc: '300mm D-shape pull handle for single-sided glass door mounting. 316 stainless steel.', priceFrom: 28, priceTo: null, priceDisplay: '£28.00', image: 'https://www.egw.co.uk/cdn/shop/files/6-inch-d-shaped-shower-door-handles_1200x1200.jpg?v=1726737804', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-door-pull-handle-1200-round', name: 'Round Pull Handle 1200mm — Entrance Door', category: 'doorHardware', shortDesc: '1200mm full-height round pull handle for glass entrance doors. 32mm diameter tube. 316 stainless steel.', priceFrom: 85, priceTo: null, priceDisplay: '£85.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Pull+Handle+1200', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-door-patch-fitting-top', name: 'Top Patch Fitting — Frameless Glass Door', category: 'doorHardware', shortDesc: 'Heavy-duty top patch fitting for frameless glass doors. Holds door panel to overhead rail or transom. For 10–12mm glass.', priceFrom: 65, priceTo: null, priceDisplay: '£65.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Top+Patch+Fitting', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-door-patch-fitting-bottom', name: 'Bottom Patch Fitting — Frameless Glass Door', category: 'doorHardware', shortDesc: 'Bottom patch fitting with pivot for frameless swing glass doors. Hydraulic self-closing mechanism. For 10–12mm glass.', priceFrom: 120, priceTo: null, priceDisplay: '£120.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Bottom+Patch+Fitting', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-door-patch-fitting-lock', name: 'Centre Lock Patch Fitting — Glass Door', category: 'doorHardware', shortDesc: 'Centre patch fitting with lock and strike plate for frameless glass doors. Keyed cylinder. For 10–12mm glass.', priceFrom: 95, priceTo: null, priceDisplay: '£95.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Lock+Patch+Fitting', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-door-pivot-set-floor-spring', name: 'Floor Spring Pivot Set — Heavy-Duty', category: 'doorHardware', shortDesc: 'Concealed floor spring pivot for heavy glass doors up to 100kg. Hydraulic closing with adjustable speed & hold-open.', priceFrom: 185, priceTo: null, priceDisplay: '£185.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Floor+Spring+Pivot', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-door-pivot-set-compact', name: 'Compact Pivot Hinge Set — Glass Door', category: 'doorHardware', shortDesc: 'Compact top and bottom pivot hinge set for interior glass doors. For 8–10mm glass. Max door weight 45kg.', priceFrom: 75, priceTo: null, priceDisplay: '£75.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Compact+Pivot+Set', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-door-push-plate-300', name: 'Push Plate 300×150mm — Glass Door', category: 'doorHardware', shortDesc: '300×150mm stainless steel push plate for glass doors. Adhesive-fixed — no drilling required. For 8–12mm glass.', priceFrom: 22, priceTo: null, priceDisplay: '£22.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Push+Plate', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-door-strike-box-keep', name: 'Strike Box Keep — Glass Door Lock', category: 'doorHardware', shortDesc: 'Wall-mounted strike box keep for glass door locks. Stainless steel construction. Adjustable for alignment.', priceFrom: 18, priceTo: null, priceDisplay: '£18.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Strike+Box', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-door-overhead-closer', name: 'Overhead Door Closer — Glass Door', category: 'doorHardware', shortDesc: 'Surface-mounted overhead door closer for glass doors. Adjustable closing speed and latching action. For doors up to 80kg.', priceFrom: 145, priceTo: null, priceDisplay: '£145.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Overhead+Closer', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
];

// ─── Partition Hardware ──────────────────────────────────────

const partitionHardware = [
  { id: 'acc-partition-clamp-wall-square', name: 'Wall Clamp — Square (Glass Partition)', category: 'partitionHardware', shortDesc: 'Square wall clamp for fixing glass partition panels. Zinc alloy with stainless steel finish. For 8–12mm glass.', priceFrom: 18, priceTo: null, priceDisplay: '£18.00', image: 'https://www.egw.co.uk/cdn/shop/products/ATB-B-S-Fbrushedbalustradeclamp_1200x655.jpg?v=1601373163', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-partition-clamp-wall-round', name: 'Wall Clamp — Round (Glass Partition)', category: 'partitionHardware', shortDesc: 'Round wall clamp for glass partition panels. Sleek disc design. 316 stainless steel. For 8–12mm glass.', priceFrom: 16, priceTo: null, priceDisplay: '£16.00', image: 'https://www.egw.co.uk/cdn/shop/products/SH-ATB-B-Dbrushedstainlesssteelroundbackbalustradeclamp_1200x655.jpg?v=1601302048', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-partition-glass-to-glass-clamp', name: 'Glass-to-Glass Clamp 90° — Partition', category: 'partitionHardware', shortDesc: '90° glass-to-glass clamp for connecting perpendicular partition panels. Zinc alloy. For 8–12mm glass.', priceFrom: 24, priceTo: null, priceDisplay: '£24.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=G2G+Clamp+90', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-partition-glass-to-glass-180', name: 'Glass-to-Glass Clamp 180° — Inline Partition', category: 'partitionHardware', shortDesc: '180° inline glass-to-glass clamp for joining partition panels in a straight line. For 8–12mm glass.', priceFrom: 22, priceTo: null, priceDisplay: '£22.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=G2G+Clamp+180', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-partition-u-channel-3000', name: 'U-Channel 3000mm — Floor/Ceiling Mount', category: 'partitionHardware', shortDesc: '3000mm aluminium U-channel for floor or ceiling mounting of glass partition panels. For 10–12mm glass.', priceFrom: 38, priceTo: null, priceDisplay: '£38.00', image: 'https://www.egw.co.uk/cdn/shop/products/blackchannel_1200x1200.jpg?v=1677168098', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Mill Finish'], brand: 'CRL' },
  { id: 'acc-partition-header-rail-3000', name: 'Header Rail 3000mm — Ceiling Mount', category: 'partitionHardware', shortDesc: '3000mm aluminium header rail for ceiling-mounted glass partitions. Concealed fixings. For 10–12mm glass.', priceFrom: 55, priceTo: null, priceDisplay: '£55.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Header+Rail+3000', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-partition-door-roller-set', name: 'Sliding Partition Door Roller Set', category: 'partitionHardware', shortDesc: 'Roller set for sliding glass partition doors. Soft-close mechanism included. For 8–10mm glass panels up to 80kg.', priceFrom: 95, priceTo: null, priceDisplay: '£95.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Partition+Roller', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-partition-track-2000', name: 'Sliding Partition Track 2000mm', category: 'partitionHardware', shortDesc: '2000mm aluminium sliding track for glass partition doors. Wall or ceiling mount. Includes end stops.', priceFrom: 65, priceTo: null, priceDisplay: '£65.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Partition+Track', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-partition-acoustic-seal', name: 'Acoustic Seal Strip — Glass Partition 5m', category: 'partitionHardware', shortDesc: '5m roll of acoustic seal strip for glass partitions. Reduces sound transmission. Clear silicone construction.', priceFrom: 18, priceTo: null, priceDisplay: '£18.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Acoustic+Seal', fitsWith: [], finishes: [], brand: 'CRL' },
];

// ─── Barn Door & Sliding Hardware ────────────────────────────

const barnDoorHardware = [
  { id: 'acc-barn-door-track-kit-2000', name: 'Barn Door Track Kit 2000mm — Glass', category: 'barnDoorHardware', shortDesc: 'Complete barn door sliding track kit for glass doors. 2000mm stainless steel rail with rollers, stops and floor guide. For 8–10mm glass.', priceFrom: 189, priceTo: null, priceDisplay: '£189.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Barn+Door+Kit+2000', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-barn-door-track-kit-2500', name: 'Barn Door Track Kit 2500mm — Glass', category: 'barnDoorHardware', shortDesc: 'Complete barn door sliding track kit. 2500mm rail for wider openings. Includes all hardware and fixing kit. For 8–10mm glass.', priceFrom: 229, priceTo: null, priceDisplay: '£229.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Barn+Door+Kit+2500', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-barn-door-roller-top-hung', name: 'Top-Hung Barn Door Roller — Pair', category: 'barnDoorHardware', shortDesc: 'Pair of premium top-hung rollers for glass barn doors. Stainless steel with sealed bearings. Silent operation.', priceFrom: 65, priceTo: null, priceDisplay: '£65.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Barn+Door+Roller', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-barn-door-soft-close-kit', name: 'Soft-Close Kit for Barn Door Track', category: 'barnDoorHardware', shortDesc: 'Retrofit soft-close damper kit for glass barn door tracks. Gentle deceleration in both directions.', priceFrom: 45, priceTo: null, priceDisplay: '£45.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Soft+Close+Kit', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-barn-door-floor-guide', name: 'Adjustable Floor Guide — Glass Barn Door', category: 'barnDoorHardware', shortDesc: 'Low-profile adjustable floor guide for glass barn doors. Prevents lateral swinging. Stainless steel.', priceFrom: 18, priceTo: null, priceDisplay: '£18.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Floor+Guide', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-barn-door-pull-handle-flush', name: 'Flush Pull Handle — Glass Barn Door', category: 'barnDoorHardware', shortDesc: 'Flush-mounted pull handle for glass barn doors. Allows door to sit flat against wall. For 8–10mm glass.', priceFrom: 28, priceTo: null, priceDisplay: '£28.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Flush+Pull', fitsWith: [], finishes: ['Chrome', 'Matt Black', 'Brushed Nickel'], brand: 'CRL' },
  { id: 'acc-barn-door-double-track-3000', name: 'Double Barn Door Track Kit 3000mm', category: 'barnDoorHardware', shortDesc: 'Double-door barn door track kit for bi-parting glass doors. 3000mm rail with 2 sets of rollers and guides.', priceFrom: 349, priceTo: null, priceDisplay: '£349.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Double+Barn+Kit', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
  { id: 'acc-barn-door-anti-jump-disc', name: 'Anti-Jump Safety Disc — Barn Door (Set of 2)', category: 'barnDoorHardware', shortDesc: 'Safety disc set preventing glass barn door from jumping off track. Required safety accessory. Set of 2.', priceFrom: 12, priceTo: null, priceDisplay: '£12.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Anti+Jump+Disc', fitsWith: [], finishes: ['Chrome', 'Matt Black'], brand: 'CRL' },
];

// ─── Glazing Tools & Supplies ────────────────────────────────

const glazingTools = [
  { id: 'acc-tool-suction-lifter-single', name: 'Single Cup Suction Lifter — 50kg', category: 'glazingTools', shortDesc: 'Professional single-cup suction lifter for glass handling. 50kg capacity. Quick-release pump action.', priceFrom: 18, priceTo: null, priceDisplay: '£18.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Suction+Lifter+1', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-tool-suction-lifter-double', name: 'Double Cup Suction Lifter — 80kg', category: 'glazingTools', shortDesc: 'Heavy-duty double-cup suction lifter for carrying large glass panels. 80kg capacity. Ergonomic handle.', priceFrom: 32, priceTo: null, priceDisplay: '£32.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Suction+Lifter+2', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-tool-suction-lifter-triple', name: 'Triple Cup Suction Lifter — 120kg', category: 'glazingTools', shortDesc: 'Professional triple-cup suction lifter for large glass sheets. 120kg capacity. Swivel handle for angling.', priceFrom: 55, priceTo: null, priceDisplay: '£55.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Suction+Lifter+3', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-tool-glass-cutter-oil', name: 'Oil-Fed Glass Cutter — Professional', category: 'glazingTools', shortDesc: 'Professional oil-fed glass cutter with tungsten carbide wheel. Self-oiling reservoir. For float glass up to 12mm.', priceFrom: 15, priceTo: null, priceDisplay: '£15.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Glass+Cutter', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-tool-glass-pliers-running', name: 'Running Pliers — Glass Breaking', category: 'glazingTools', shortDesc: 'Running pliers for cleanly breaking scored glass along the cutting line. Wide jaw for even pressure.', priceFrom: 12, priceTo: null, priceDisplay: '£12.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Running+Pliers', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-tool-glass-pliers-grozing', name: 'Grozing Pliers — Glass Nibbling', category: 'glazingTools', shortDesc: 'Grozing pliers for nibbling and removing small glass edges. Serrated flat jaws. Essential glazing tool.', priceFrom: 10, priceTo: null, priceDisplay: '£10.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Grozing+Pliers', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-tool-corner-protectors-50', name: 'Glass Corner Protectors — Pack of 50', category: 'glazingTools', shortDesc: 'Foam corner protectors for safe transport and storage of glass panels. Pack of 50. Fits glass up to 19mm.', priceFrom: 14, priceTo: null, priceDisplay: '£14.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Corner+Protectors', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-tool-glass-edge-hand-pad', name: 'Diamond Hand Pad — Glass Edge Smoothing', category: 'glazingTools', shortDesc: 'Diamond abrasive hand pad for smoothing glass edges after cutting. Medium grit. Wet or dry use.', priceFrom: 9, priceTo: null, priceDisplay: '£9.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Diamond+Hand+Pad', fitsWith: [], finishes: [], brand: 'CRL' },
  { id: 'acc-tool-measuring-tape-5m', name: 'Glass Measuring Tape 5m — Metric', category: 'glazingTools', shortDesc: '5m steel measuring tape with glass-safe end hook. Metric markings. Belt clip. Essential for templating.', priceFrom: 6, priceTo: null, priceDisplay: '£6.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Measuring+Tape', fitsWith: [], finishes: [], brand: 'P&J Glass' },
  { id: 'acc-tool-spirit-level-600', name: 'Spirit Level 600mm — Aluminium', category: 'glazingTools', shortDesc: '600mm aluminium spirit level for glass installation. 3 vials. Essential for shower screens, balustrades and mirrors.', priceFrom: 14, priceTo: null, priceDisplay: '£14.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Spirit+Level', fitsWith: [], finishes: [], brand: 'P&J Glass' },
];

// ─── Shower Screen Systems ───────────────────────────────────

const showerEnclosures = [
  { id: 'acc-shower-screen-walkin-900', name: 'Walk-In Wetroom Panel 900mm — 8mm Glass', category: 'showerEnclosures', shortDesc: '900mm frameless walk-in wetroom panel. 8mm toughened safety glass. Includes wall profile and support bar. 1950mm high.', priceFrom: 289, priceTo: null, priceDisplay: '£289.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Walk-In+900', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'P&J Glass' },
  { id: 'acc-shower-screen-walkin-1200', name: 'Walk-In Wetroom Panel 1200mm — 8mm Glass', category: 'showerEnclosures', shortDesc: '1200mm frameless walk-in wetroom panel. 8mm toughened safety glass. Wall profile, support bar and floor seal included.', priceFrom: 349, priceTo: null, priceDisplay: '£349.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Walk-In+1200', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'P&J Glass' },
  { id: 'acc-shower-screen-crittall-900', name: 'Crittall-Style Grid Screen 900mm — Matt Black', category: 'showerEnclosures', shortDesc: '900mm Crittall-style grid shower screen with matt black frame. Industrial-look panel. 8mm toughened glass. 1950mm high.', priceFrom: 379, priceTo: null, priceDisplay: '£379.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Crittall+900', fitsWith: ['bathScreens'], finishes: ['Matt Black'], brand: 'P&J Glass' },
  { id: 'acc-shower-screen-crittall-1200', name: 'Crittall-Style Grid Screen 1200mm — Matt Black', category: 'showerEnclosures', shortDesc: '1200mm Crittall-style grid shower screen. Statement matt black frame with 8mm clear toughened glass. 1950mm high.', priceFrom: 449, priceTo: null, priceDisplay: '£449.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Crittall+1200', fitsWith: ['bathScreens'], finishes: ['Matt Black'], brand: 'P&J Glass' },
  { id: 'acc-shower-screen-fluted-900', name: 'Fluted Glass Screen 900mm — Walk-In', category: 'showerEnclosures', shortDesc: '900mm walk-in shower screen with fluted (reeded) glass. Chrome wall profile and support bar. 8mm glass, 1950mm high.', priceFrom: 399, priceTo: null, priceDisplay: '£399.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Fluted+Screen+900', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Brushed Nickel'], brand: 'P&J Glass' },
  { id: 'acc-shower-screen-sliding-1200', name: 'Sliding Shower Screen 1200mm — Frameless', category: 'showerEnclosures', shortDesc: '1200mm single-sliding frameless shower screen. Smooth-glide rollers, easy-clean glass coating. 8mm glass, 1950mm high.', priceFrom: 429, priceTo: null, priceDisplay: '£429.00', image: 'https://placehold.co/600x600/1a2055/5ec4d4.png?text=Sliding+Screen+1200', fitsWith: ['bathScreens'], finishes: ['Chrome', 'Matt Black'], brand: 'P&J Glass' },
];

// ─── Sale Pricing Helper ─────────────────────────────────────

function withSalePricing(product) {
  const saleFrom = getSalePrice(product.priceFrom);
  const saleTo = product.priceTo ? getSalePrice(product.priceTo) : null;
  const salePriceDisplay = saleTo && saleTo !== saleFrom
    ? `£${saleFrom.toFixed(2)} – £${saleTo.toFixed(2)}`
    : `£${saleFrom.toFixed(2)}`;
  return {
    ...product,
    onSale: true,
    originalPriceFrom: product.priceFrom,
    originalPriceTo: product.priceTo,
    originalPriceDisplay: product.priceDisplay,
    priceFrom: saleFrom,
    priceTo: saleTo,
    priceDisplay: salePriceDisplay,
  };
}

// ─── Helper Functions ────────────────────────────────────────

export function getAllAccessories() {
  return [...showerAccessories, ...mirrorAccessories, ...balustradeAccessories, ...sealantsCleaning, ...doorHardware, ...partitionHardware, ...barnDoorHardware, ...glazingTools, ...showerEnclosures].map(withSalePricing);
}

export function getAccessoriesByCategory(category) {
  const map = { showerAccessories, mirrorAccessories, balustradeAccessories, sealantsCleaning, doorHardware, partitionHardware, barnDoorHardware, glazingTools, showerEnclosures };
  return (map[category] || []).map(withSalePricing);
}

export function getAccessoryById(id) {
  const raw = [...showerAccessories, ...mirrorAccessories, ...balustradeAccessories, ...sealantsCleaning, ...doorHardware, ...partitionHardware, ...barnDoorHardware, ...glazingTools, ...showerEnclosures].find((p) => p.id === id);
  return raw ? withSalePricing(raw) : undefined;
}

export function getAccessoriesForCategory(productCategory) {
  // Find accessories that "fit with" a given glass product category
  const all = getAllAccessories();
  return all.filter((a) => a.fitsWith && a.fitsWith.includes(productCategory));
}
