// P&J GLASS - PROJECT DATABASE
// 20 high-quality fictional London/Essex project case studies

export const projects = [
  {
    slug: 'kensington-townhouse-balustrade',
    title: 'Kensington Townhouse',
    subtitle: 'Full-height frameless glass balustrade for a Grade II listed terrace',
    location: 'Kensington, London W8',
    category: 'Glass Balustrades',
    year: '2024',
    scope: 'Residential',
    description: 'A meticulous restoration project on a Grade II listed Victorian townhouse required frameless glass balustrades that complemented the period architecture without compromising sightlines across the garden terrace. We used 17mm toughened laminated glass with concealed channel fixings and polished edges, maintaining the building\u2019s heritage character while meeting modern safety requirements.',
    services: ['Frameless Glass Balustrades', 'Site Survey', 'Bespoke Manufacture', 'Professional Installation'],
    specs: ['17mm Toughened Laminate Glass', 'Concealed Channel System', 'BS 6180:2011 Compliant', 'Polished Edges'],
    image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c30f8bf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'P&J Glass understood exactly what we needed. The balustrade is invisible \u2014 it lets the architecture speak for itself.', author: 'Charlotte Whitfield', role: 'Homeowner' },
  },
  {
    slug: 'islington-kitchen-splashback',
    title: 'Islington Kitchen Refit',
    subtitle: 'Bespoke copper metallic painted glass splashback for a modern open-plan kitchen',
    location: 'Islington, London N1',
    category: 'Kitchen Splashbacks',
    year: '2024',
    scope: 'Residential',
    description: 'This Victorian terrace conversion in Islington features a sleek open-plan kitchen-diner. We supplied and fitted a 3.2-metre copper metallic painted glass splashback behind the induction hob and work surface. The metallic shimmer finish catches the light from the glass roof lantern above, creating a warm focal point.',
    services: ['Painted Glass Splashback', 'Colour Matching', 'Template & Fit', 'Cutouts for Sockets'],
    specs: ['6mm Toughened Low-Iron Glass', 'Copper Metallic Paint Finish', 'Heat Resistant to 400\u00b0C', '3200x750mm Single Panel'],
    image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The copper splashback is the talking point of our kitchen. Every guest comments on it.', author: 'David & Rachel Chen', role: 'Homeowners' },
  },
  {
    slug: 'chelsea-penthouse-mirrors',
    title: 'Chelsea Penthouse',
    subtitle: 'Floor-to-ceiling antiqued mirror feature wall in a luxury penthouse',
    location: 'Chelsea, London SW3',
    category: 'Mirrors',
    year: '2024',
    scope: 'Residential',
    description: 'Working with an interior design studio, we created a dramatic floor-to-ceiling antiqued mirror feature wall spanning 5 metres in a Chelsea penthouse. The oversized panels create an illusion of infinite space in the living area, reflecting the Thames views across the room.',
    services: ['Custom Mirror Panels', 'Antiqued Finish', 'Structural Assessment', 'Precision Installation'],
    specs: ['6mm Silver Mirror Glass', 'Antiqued Finish', '5000x2800mm Total Area', 'Safety Vinyl Backing'],
    image: 'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The mirror wall transformed the entire apartment. It doubled the sense of space and light.', author: 'Sophie Laurent', role: 'Interior Designer' },
  },
  {
    slug: 'canary-wharf-office-partitions',
    title: 'Canary Wharf Commercial Fit-Out',
    subtitle: 'Frameless glass partitions and meeting room walls for a FinTech headquarters',
    location: 'Canary Wharf, London E14',
    category: 'Glass Partitions',
    year: '2024',
    scope: 'Commercial',
    description: 'A fast-growing FinTech company required a complete glass partition system for their new 8,000 sq ft office. We installed frameless toughened glass partitions to create private meeting rooms, phone booths, and executive offices while maintaining the open, collaborative feel of the workspace.',
    services: ['Frameless Glass Partitions', 'Acoustic Glass Options', 'Manifestation Design', 'Full Fit-Out'],
    specs: ['12mm Toughened Glass', 'Acoustic Rating 38dB', 'Frameless System', '320 sq m Glass Area'],
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'Excellent delivery under tight deadlines. The glass partitions look premium and the acoustics are superb.', author: 'Marcus Reid', role: 'Facilities Manager' },
  },
  {
    slug: 'mayfair-juliet-balcony',
    title: 'Mayfair Residence',
    subtitle: 'Oversized Juliet balcony system for French doors overlooking a private garden',
    location: 'Mayfair, London W1',
    category: 'Juliet Balconies',
    year: '2024',
    scope: 'Residential',
    description: 'This Mayfair residence required an oversized Juliet balcony spanning 3.5 metres to complement newly installed French doors on the first floor. We used toughened laminated glass with a brushed stainless steel top-mount system, creating a near-invisible barrier that preserves the uninterrupted garden views.',
    services: ['Oversized Juliet Balcony', 'Site Survey', 'Building Control Liaison', 'Installation'],
    specs: ['Toughened Laminate Glass', 'Top-Mount Stainless System', '3500mm Width', 'Building Regs Compliant'],
    image: 'https://images.unsplash.com/photo-1600607687939-ce8a6c30f8bf?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c30f8bf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'Seamless from survey to sign-off. The balcony is exactly what we envisioned.', author: 'Jonathan Hale', role: 'Homeowner' },
  },
  {
    slug: 'shoreditch-restaurant-splashback',
    title: 'Shoreditch Restaurant',
    subtitle: 'Black marble effect printed glass splashback for an open kitchen',
    location: 'Shoreditch, London E1',
    category: 'Kitchen Splashbacks',
    year: '2024',
    scope: 'Commercial',
    description: 'A new restaurant in Shoreditch features an open kitchen visible to diners. We supplied a 4-metre black marble printed glass splashback that serves as both a functional heat shield and a dramatic design statement behind the cooking stations.',
    services: ['Printed Glass Splashback', 'Commercial Template', 'Heat-Resistant Installation', 'Joint-Free Design'],
    specs: ['6mm Toughened Glass', 'Black Marble HD Print', 'Heat Resistant to 400\u00b0C', '4000x900mm'],
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The marble splashback sets the tone for the entire restaurant. Stunning quality.', author: 'Olivia Santos', role: 'Restaurant Owner' },
  },
  {
    slug: 'brentwood-shower-enclosure',
    title: 'Brentwood Master Bath',
    subtitle: 'Frameless walk-in shower enclosure with matt black hardware',
    location: 'Brentwood, Essex',
    category: 'Bath Screens',
    year: '2024',
    scope: 'Residential',
    description: 'A complete master bathroom renovation in Brentwood centred around a stunning frameless walk-in shower. We installed 8mm toughened glass with matt black hinges and brackets, creating a luxurious wet-room feel while containing the water effectively.',
    services: ['Frameless Shower Screen', 'Matt Black Hardware', 'Wet Room Design', 'Waterproofing Consultation'],
    specs: ['8mm Toughened Glass', 'Matt Black Hinges & Brackets', '1200x2000mm Panel', 'Drip Seal Included'],
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The shower looks incredible. The matt black hardware against the clear glass is so elegant.', author: 'Laura & Mark Atkins', role: 'Homeowners' },
  },
  {
    slug: 'richmond-staircase-balustrade',
    title: 'Richmond Hill House',
    subtitle: '10mm clear glass balustrade wrapping a cantilevered oak staircase',
    location: 'Richmond, London TW10',
    category: 'Glass Balustrades',
    year: '2023',
    scope: 'Residential',
    description: 'This new-build home features a stunning cantilevered oak staircase spanning three floors. We designed and installed 10mm clear toughened glass balustrade panels with concealed base shoe fixings, allowing the craftsmanship of the oak to take centre stage.',
    services: ['Glass Staircase Balustrade', 'Base Shoe System', '3-Floor Installation', 'Bespoke Panel Sizes'],
    specs: ['10mm Toughened Glass', 'Base Shoe Channel Fixing', '28 Individual Panels', 'Polished Edges'],
    image: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'Three floors of glass and not a single issue. The staircase is the heart of our home.', author: 'Tom & Jess Hargrove', role: 'Homeowners' },
  },
  {
    slug: 'hampstead-gym-mirrors',
    title: 'Hampstead Home Gym',
    subtitle: 'Full-wall gym mirrors with safety backing for a basement fitness suite',
    location: 'Hampstead, London NW3',
    category: 'Mirrors',
    year: '2023',
    scope: 'Residential',
    description: 'We transformed a dark basement into a high-end home gym with floor-to-ceiling mirrors spanning two walls. The 6mm silver mirror glass with safety vinyl backing creates the illusion of a bright, open space and allows the owner to monitor form during workouts.',
    services: ['Large Format Gym Mirrors', 'Safety Vinyl Backing', 'Wall Preparation', 'Seamless Installation'],
    specs: ['6mm Silver Mirror Glass', 'Safety Vinyl Backing', '16 sq m Total Area', 'Adhesive & Mechanical Fix'],
    image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The mirrors completely changed the feel of the basement. It feels twice the size now.', author: 'Daniel Okonkwo', role: 'Homeowner' },
  },
  {
    slug: 'romford-showroom-splashbacks',
    title: 'P&J Glass Showroom Refresh',
    subtitle: 'New splashback display featuring 12 live colour samples',
    location: 'Romford, Essex RM6',
    category: 'Kitchen Splashbacks',
    year: '2024',
    scope: 'Commercial',
    description: 'We refreshed our own showroom at 1181 High Rd with a new splashback display wall featuring 12 live colour samples. Customers can see and touch real painted and printed glass samples in situ before making their selection.',
    services: ['Display Design', 'Sample Production', 'Showroom Fit-Out', 'Lighting Integration'],
    specs: ['12 Display Panels', 'Painted & Printed Options', 'LED Backlighting', 'Rotating Seasonal Colours'],
    image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'Being able to see the real colours in person made our decision so much easier.', author: 'Karen Mitchell', role: 'Customer' },
  },
  {
    slug: 'greenwich-balcony-balustrade',
    title: 'Greenwich Waterfront Apartment',
    subtitle: '12mm toughened glass balcony balustrades with river views',
    location: 'Greenwich, London SE10',
    category: 'Glass Balustrades',
    year: '2023',
    scope: 'Residential',
    description: 'A waterfront apartment in Greenwich required 12mm toughened glass balcony balustrades to replace aging metal railings. The new glass panels maximise the spectacular Thames and Canary Wharf views while meeting coastal wind-loading requirements.',
    services: ['Balcony Balustrades', 'Wind Load Calculation', 'Marine-Grade Fixings', 'Installation'],
    specs: ['12mm Toughened Glass', 'Stainless Steel 316 Fixings', '6 Balcony Panels', 'Wind Load Compliant'],
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c30f8bf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'We can finally enjoy our river views without those old metal bars in the way. Stunning result.', author: 'Amir & Priya Patel', role: 'Homeowners' },
  },
  {
    slug: 'notting-hill-gold-splashback',
    title: 'Notting Hill Victorian Kitchen',
    subtitle: 'Gold marble printed glass splashback in a period kitchen renovation',
    location: 'Notting Hill, London W11',
    category: 'Kitchen Splashbacks',
    year: '2024',
    scope: 'Residential',
    description: 'A period kitchen renovation in Notting Hill called for a luxurious gold marble printed glass splashback spanning the full width of the cooking area. The high-resolution print perfectly mimics natural gold-veined marble at a fraction of the cost and maintenance.',
    services: ['Printed Glass Splashback', 'Full-Width Template', 'Socket Cutouts', 'Same-Day Installation'],
    specs: ['6mm Toughened Glass', 'Gold Marble HD Print', '2800x750mm', 'UV Stable Inks'],
    image: 'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566752547-33a038569773?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'It looks exactly like real marble. Everyone assumes it\u2019s stone until we tell them.', author: 'Isabella Crawford', role: 'Homeowner' },
  },
  {
    slug: 'chigwell-outdoor-balustrade',
    title: 'Chigwell Garden Terrace',
    subtitle: 'Bronze tinted 10mm glass balustrade for a raised garden deck',
    location: 'Chigwell, Essex',
    category: 'Glass Balustrades',
    year: '2023',
    scope: 'Residential',
    description: 'A newly built raised composite decking area in Chigwell needed glass balustrades. We recommended 10mm bronze tinted glass for its warm appearance and natural UV filtering properties, complementing the dark timber tones of the deck.',
    services: ['Tinted Glass Balustrade', 'Post System Supply', 'Outdoor Installation', 'Weather Sealing'],
    specs: ['10mm Bronze Tinted Glass', 'Stainless Steel Posts', '14 Linear Metres', 'Outdoor Grade'],
    image: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The bronze tint was a brilliant suggestion. It ties the whole garden design together.', author: 'Steve & Claire Barton', role: 'Homeowners' },
  },
  {
    slug: 'battersea-new-build-juliet',
    title: 'Battersea New Build Development',
    subtitle: 'Juliet balconies for 24 apartments in a riverside new-build scheme',
    location: 'Battersea, London SW11',
    category: 'Juliet Balconies',
    year: '2023',
    scope: 'Commercial',
    description: 'We supplied and installed Juliet balcony systems for 24 apartments across a new-build riverside development in Battersea. Working closely with the main contractor, all units were fitted within a 3-week programme to keep the build on schedule.',
    services: ['Juliet Balcony Supply', 'Multi-Unit Programme', 'Contractor Coordination', 'Building Control Sign-Off'],
    specs: ['Toughened Laminate Glass', 'Top-Mount Aluminium Profiles', '24 Units', '1500mm & 2000mm Widths'],
    image: 'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c30f8bf?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'P&J delivered all 24 units on time and within budget. Reliable trade partner.', author: 'Gary Morris', role: 'Site Manager, Weston Construction' },
  },
  {
    slug: 'tower-bridge-penthouse-shower',
    title: 'Tower Bridge Penthouse',
    subtitle: 'Bespoke frameless shower enclosure with fixed and hinged panels',
    location: 'Tower Bridge, London SE1',
    category: 'Bath Screens',
    year: '2024',
    scope: 'Residential',
    description: 'A luxury penthouse bathroom renovation at Tower Bridge required a bespoke frameless shower enclosure with a combination of fixed and hinged panels, wrapping around a freestanding rain shower. All glass was 10mm toughened with chrome hardware.',
    services: ['Bespoke Shower Enclosure', 'Template Service', 'Chrome Hardware', 'Waterproof Installation'],
    specs: ['10mm Toughened Glass', 'Chrome Hinges & Brackets', '3-Panel Configuration', 'Ceiling-to-Floor'],
    image: 'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The shower enclosure is a work of art. Absolutely perfect execution.', author: 'Rebecca Young', role: 'Homeowner' },
  },
  {
    slug: 'hackney-warehouse-mirrors',
    title: 'Hackney Warehouse Conversion',
    subtitle: 'Oversized arch leaner mirrors and feature mirror wall in a loft apartment',
    location: 'Hackney, London E8',
    category: 'Mirrors',
    year: '2024',
    scope: 'Residential',
    description: 'This warehouse conversion loft apartment needed oversized mirrors to balance the vast open-plan space. We supplied two 2-metre arch leaner mirrors for the bedroom and created a segmented mirror feature wall in the living area using frameless panels.',
    services: ['Arch Leaner Mirrors', 'Mirror Feature Wall', 'Delivery & Placement', 'Wall-Mount Installation'],
    specs: ['6mm Silver Mirror Glass', '2x Arch Leaner 800x2000mm', 'Feature Wall 3200x1800mm', 'Safety Backed'],
    image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The arch mirrors are absolutely gorgeous. They make the loft feel even more spacious.', author: 'Zara Thompson', role: 'Homeowner' },
  },
  {
    slug: 'hornchurch-patio-doors-juliet',
    title: 'Hornchurch Family Home',
    subtitle: 'Juliet balcony and frosted glass balustrade for new patio doors',
    location: 'Hornchurch, Essex',
    category: 'Juliet Balconies',
    year: '2023',
    scope: 'Residential',
    description: 'After installing new bi-fold patio doors on the first floor, this family home needed a Juliet balcony for safety compliance. We fitted a 2.5-metre Juliet balcony with satin frosted glass for partial privacy from neighbouring properties.',
    services: ['Juliet Balcony Installation', 'Satin Frosted Glass', 'Building Regs Compliance', 'Same-Week Turnaround'],
    specs: ['Satin Frosted Laminate Glass', 'Side-Mount Aluminium Profiles', '2500mm Width', 'Grey Powder Coat'],
    image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'Quick turnaround and exactly what we needed for building control sign-off.', author: 'Paul & Helen Edwards', role: 'Homeowners' },
  },
  {
    slug: 'wimbledon-rose-gold-splashback',
    title: 'Wimbledon Kitchen Extension',
    subtitle: 'Rose gold metallic painted glass splashback in a rear kitchen extension',
    location: 'Wimbledon, London SW19',
    category: 'Kitchen Splashbacks',
    year: '2024',
    scope: 'Residential',
    description: 'A newly built rear extension in Wimbledon features a stunning rose gold metallic painted glass splashback. The warm shimmer harmonises beautifully with the brushed brass tap fittings and pale grey cabinets chosen by the homeowner.',
    services: ['Painted Glass Splashback', 'Rose Gold Metallic Finish', 'Extension Consultation', 'Precision Fit'],
    specs: ['6mm Toughened Low-Iron Glass', 'Rose Gold Metallic Paint', '2400x750mm', 'Socket Cutouts'],
    image: 'https://images.unsplash.com/photo-1600566752547-33a038569773?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600566752547-33a038569773?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'The rose gold matches our brass fittings perfectly. The kitchen now feels like a show home.', author: 'Natalie Brooks', role: 'Homeowner' },
  },
  {
    slug: 'stratford-hotel-bath-screens',
    title: 'Stratford Boutique Hotel',
    subtitle: 'Frameless bath screens and shower enclosures across 40 guest rooms',
    location: 'Stratford, London E20',
    category: 'Bath Screens',
    year: '2023',
    scope: 'Commercial',
    description: 'A boutique hotel near the Olympic Park specified frameless 8mm glass bath screens for all 40 guest bathrooms. We coordinated the phased delivery and installation across 6 weeks, working around the hotel\u2019s room-by-room renovation programme.',
    services: ['Bulk Bath Screen Supply', 'Phased Installation', 'Commercial Specification', 'Project Management'],
    specs: ['8mm Toughened Glass', 'Chrome Hinges', '40 Units', '800x1400mm Standard'],
    image: 'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600489000022-c2086d79f9d4?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'P&J managed the entire programme flawlessly. All 40 rooms completed on schedule.', author: 'Diane Fletcher', role: 'Hotel General Manager' },
  },
  {
    slug: 'epping-table-top-glass',
    title: 'Epping Period Dining Room',
    subtitle: 'Custom 10mm toughened glass table top protectors for antique furniture',
    location: 'Epping, Essex',
    category: 'Table Top Glass',
    year: '2024',
    scope: 'Residential',
    description: 'The owners of a stunning Edwardian dining set wanted to protect the original mahogany table surface without hiding it. We cut and polished 10mm toughened glass tops for the dining table, sideboard, and hall console \u2014 all custom-sized with rubber bumper feet.',
    services: ['Custom Table Top Glass', 'Precision Cutting', 'Edge Polishing', 'Rubber Feet Supply'],
    specs: ['10mm Toughened Glass', 'Rectangle & Custom Shapes', '3 Pieces Total', 'Crystal Clear Finish'],
    image: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1200&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=800&auto=format&fit=crop&q=80',
    ],
    testimonial: { text: 'We can now use our antique table without worry. The glass is invisible \u2014 you can\u2019t tell it\u2019s there.', author: 'Robert & Janet Price', role: 'Homeowners' },
  },
];

export function getProjectBySlug(slug) {
  return projects.find((p) => p.slug === slug);
}

export function getAllProjectSlugs() {
  return projects.map((p) => p.slug);
}
